#!/bin/bash
#
# This is based on the deploy script in 
# 
# https://github.com/awslabs/ecs-refarch-continuous-deployment
#
# Creates a subdirectory bucket for the landscape
#
# deploy profile bucket lanscape
# example ./deploy w2c-non-prod buaws-web2cloud-nonprod test
# NOTE MAY NEED TO RUN TWICE! (because of lag in create bucket)

set -o errexit -o xtrace

#region="us-east-1"
#bucket=ecs-refarch-continuous-deployment-v2
regions=(
#  ap-northeast-1
#  ap-southeast-1
#  ap-southeast-2                                                                                                                 
#  ca-central-1                                                                                                                   
#  eu-central-1                                                                                                                   
#  eu-west-1                                                                                                                      
#  eu-west-2                                                                                                                      
us-east-1                                                                                                                      
#  us-east-2                                                                                                                      
#  us-west-1                                                                                                                      
us-west-2
#ws-waf-security-automations  us-west-2                                                                                           
)                                                                                                                                

aws="aws"
if [ "x$1" = "x-d" ]; then
  aws="echo $aws"
  shift
fi

profile="$1"
shift
bucket="$1"
shift
#landscape="$1"
#shift
path="templates"
if [ "x$1" != "x" ]; then
  path="$1"
fi

if [ "x$profile" != "x-" ]; then
  aws="$aws --profile $profile"
fi

for region in "${regions[@]}"                                                                                                    
do

 $aws s3api head-bucket --bucket "${bucket}-${region}" --region "$region" ||
   $aws s3 mb "s3://${bucket}-${region}" --region "$region"
 $aws s3api put-bucket-policy \
   --bucket "${bucket}-${region}" \
   --policy "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:GetObject\",\"s3:GetObjectVersion\"],\"Resource\":\"arn:aws:s3:::${bucket}-${region}/*\"},{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:ListBucket\",\"s3:GetBucketVersioning\"],\"Resource\":\"arn:aws:s3:::${bucket}-${region}\"}]}" \
   --region "$region"

 $aws s3api put-bucket-versioning \
   --bucket "${bucket}-${region}" \
   --versioning-configuration Status=Enabled \
   --region "$region"

# $aws s3 cp ecs-refarch-continuous-deployment.yaml "s3://${bucket}-${region}" \
#   --region "$region"

 $aws s3 cp --recursive templates/ "s3://${bucket}-${region}/$path" \
   --region "$region"
done
exit

#bucket=ecs-refarch-continuous-deployment-v2
#regions=(
#  ap-northeast-1
#  ap-southeast-1
#  ap-southeast-2
#  ca-central-1
#  eu-central-1
#  eu-west-1
#  eu-west-2
#  us-east-1
#  us-east-2
#  us-west-1
#ws-waf-security-automations  us-west-2
#)

#for region in "${regions[@]}"
#do
#  aws s3api head-bucket --bucket "${bucket}-${region}" --region "$region" ||
#    aws s3 mb "s3://${bucket}-${region}" --region "$region"
#
#  aws s3api put-bucket-policy \
#    --bucket "${bucket}-${region}" \
#    --policy "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:GetObject\",\"s3:GetObjectVersion\"],\"Resource\":\"arn:aws:s3:::${bucket}-${region}/*\"},{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:ListBucket\",\"s3:GetBucketVersioning\"],\"Resource\":\"arn:aws:s3:::${bucket}-${region}\"}]}" \
#    --region "$region"
#
#  aws s3api put-bucket-versioning \
#    --bucket "${bucket}-${region}" \
#    --versioning-configuration Status=Enabled \
#    --region "$region"
#
#  aws s3 cp ecs-refarch-continuous-deployment.yaml "s3://${bucket}-${region}" \
#    --region "$region"
#
#  aws s3 cp --recursive templates/ "s3://${bucket}-${region}/templates" \
#    --region "$region"
#done
